iso:
  uefi:
    - channel:live/grub2-efi-image
  image:
    - channel:live/grub2
    - channel:live/grub2-efi-image
  label: "COS_LIVE"
#image_prefix: "distro"
date: true
repositories:
  - uri: quay.io/costoolkit/releases-green
    arch: "x86_64"
    name: cOS
